### ISSUE TITLE
Missing `spread` in `EffectShadow_` type

### ISSUE THREAD

**Issue by markevans** [didoo/figma-api#18]
Hi - thanks for this very useful library!

Drop shadows in Figma have a "spread" property https://www.figma.com/developers/api#effect-type.

I guess this needs to be added (as a `number`) to `EffectShadow_` in https://github.com/didoo/figma-api/blob/master/src/ast-types.ts#L318

I didn't do a PR because I wasn't sure - let me know if you want me to - thanks!

**Comment by markevans** [comment]
(also it should be optional)

**Comment by didoo** [comment]
@markevans yes, if you can do a PR that would be great :)
