### ISSUE TITLE
Axios vulnerability

### ISSUE THREAD

**Issue by TomasHnidek** [didoo/figma-api#19]
Hi, 
can you please publish the 1.6.0 version to npm? I see that there have been changes in the repo to update Axios to correct version, however that version haven't been yet published, as latest is still 1.5.5.

Thanks,
Tomas

**Comment by didoo** [comment]
Hi @TomasHnidek I have just published version 1.6.0 on npm:
https://www.npmjs.com/package/figma-api

Can you check if everything is OK now? thanks
