### ISSUE TITLE
Expose the results types of the API calls

### ISSUE THREAD

**Issue by Kerumen** [didoo/figma-api#4]
I would like to use the return type of the `getFile` call in a state but I can't, `GetFileResult` is not exposed on the lib. I must import it from `figma-api/lib/api-types`.

```ts
import { GetFileResult } from 'figma-api/lib/api-types'

const [file, setFile] = useState<GetFileResult | null>(null)

const figmaFile = await api.getFile(fileKey)
setFile(figmaFile)
```

It would be nice to expose thoses types publicly, and all the others as well.

**Comment by didoo** [comment]
@Kerumen is this still relevant for you? if yes, can you explain me a little bit more what you need/mean? 
from what I see, the types are exposed in the `api-types` file. what do you need instead?

**Comment by didoo** [comment]
Closing this for now (in case is needed we can re-open it later)

**Comment by Kerumen** [comment]
@didoo sorry to not have answered earlier. I meant to expose the types in the top level export to be able to do

```js
import * as Figma from 'figma-api';

...

Figma.Api / Figma.GetFileResult
```

instead of

```js
import * as Figma from 'figma-api';
import { GetFileResult } from 'figma-api/lib/api-types'

Figma.Api / GetFileResult
```

You can take inspirations from [this library](https://github.com/jongold/figma-js) where the internal types (`Figma.FileResponse`, `Figma.FileImageResponse`, etc) and the Figma types are exposed (`Figma.Node`, `Figma.Canvas`, etc) which is very convenient.
