### ISSUE TITLE
Update "file.components" type

### ISSUE THREAD

**Issue by isaiahtaylor** [didoo/figma-api#50]
Hi, thank you so much for this fantastic library! I noticed that `GetFileResult.components` has this type:

```ts
/** An arrangement of published UI elements that can be instantiated across figma files */
export interface Component {
    /** The key of the component */
    key: string;
    /** The name of the component */
    name: string;
    /** The description of the component as entered in the editor */
    description: string;
}
```

However, here's the JSON output of a request:

```json
{
    "componentSetId": "2:135",
    "description": "",
    "documentationLinks": [],
    "key": "<redacted>",
    "name": "name redacted"
}
```

You can see that "componentSetId" seems to be missing. Thanks!

**Comment by jackneer** [comment]
based on [the official document](https://www.figma.com/developers/api), Component should be like this
![Screenshot from 2022-10-08 09-33-40](https://user-images.githubusercontent.com/6252713/194681165-6c61d6c4-0bae-4c85-9f70-7a2514897b01.png)
I'd like to help. May I take this?

**Comment by didoo** [comment]
Fixed in this commit https://github.com/didoo/figma-api/commit/512b0f654f874fa0c80da2bec3d15175d8d063cf.

See closed PR for details.
