### ISSUE TITLE
styles map missing from FRAME nodes

### ISSUE THREAD

**Issue by isaiahtaylor** [didoo/figma-api#52]
This is actually an error in the Figma documentation, so I understand why the type is missing from the library. I've alerted Figma to the bug.

The `StylesMap` you can find at `Node<'VECTOR'>.styles` should also exist at `Node<'FRAME'>.styles`, at the very least. However I suspect that it should also be on other types as well; probably anything that you can set styles on. I've only verified so far that is returned in FRAME nodes.

**Comment by didoo** [comment]
@isaiahtaylor if you are still interested (and you're still using the library) I just released the `2.0.0-beta` version of the library which aligns as much as possible with the existing Figma REST API endpoints (https://www.figma.com/developers/api#intro) and uses https://github.com/figma/rest-api-spec under the hood (so the types signatures should be the official ones.
