### ISSUE TITLE
Variables Endpoint

### ISSUE THREAD

**Issue by LouiFi** [didoo/figma-api#61]
https://www.figma.com/developers/api#variables

The new "Variables" feature born in Figma, can we add it to this really usefull package ?

**Comment by andreasschiestl** [comment]
I have implementes the Variables Endpoint and will be happy to provide a pull request but it looks like @didoo is no longer active?

**Comment by chris2cant** [comment]
Do we have some news ? 😁

**Comment by p-drolima** [comment]
hey.... actually would also want that endpoint! :)

Thank you for you efforts!

**Comment by p-drolima** [comment]
I might contribute to this with a pull request. will keep you in loop

**Comment by p-drolima** [comment]
ok, one thing I found out, seems that Figma restricts local variable requests only for enterprise level plans. Which leads me to conclude this will not be possible and probably the reason why contributors of this repo never bothered perhaps

**Comment by didoo** [comment]
@LouiFi @chris2cant @p-drolima if you are still interested (and you're still using the library) I just released the `2.0.0-beta` version of the library which aligns as much as possible with the existing Figma REST API endpoints (https://www.figma.com/developers/api#intro) and uses https://github.com/figma/rest-api-spec under the hood (so the types signatures should be the official ones.

**Comment by LouiFi** [comment]
Nice!

Thank you so much I am still using your work 🙏
